---
- hosts: ec2-54-210-177-96.compute-1.amazonaws.com
  user: ubuntu
  tasks:
    - name: playbook_test
      shell: touch /tmp/playbook123.txt
    - name: echo test
      shell: echo '123' > /tmp/echo_test.txt
    
  roles:
    - jdk8
